In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

In [2]:
df = pd.read_csv("../dataset/taxi_trip_pricing.csv")

df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [3]:
df.isnull().sum()

Trip_Distance_km         50
Time_of_Day              50
Day_of_Week              50
Passenger_Count          50
Traffic_Conditions       50
Weather                  50
Base_Fare                50
Per_Km_Rate              50
Per_Minute_Rate          50
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [4]:
df = df.dropna()

df.shape

(562, 11)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
categorical_columns = [
    "Time_of_Day",
    "Day_of_Week",
    "Traffic_Conditions",
    "Weather"
]

In [7]:
label_encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

In [8]:
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2,0,3.0,1,0,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,1,1.0,0,0,2.70,1.21,0.15,37.27,52.9032
5,8.64,0,1,2.0,2,0,2.55,1.71,0.48,89.33,60.2028
12,41.79,3,1,3.0,0,0,4.60,1.77,0.11,86.95,88.1328
14,9.91,1,0,2.0,0,0,2.32,1.26,0.34,41.72,28.9914

memisahkan feature dan target

In [9]:
X = df.drop("Trip_Price", axis=1)

y = df["Trip_Price"]

In [10]:
print(X.head())

print(y.head())

    Trip_Distance_km  Time_of_Day  Day_of_Week  Passenger_Count  \
0              19.35            2            0              3.0
2              36.87            1            1              1.0
5               8.64            0            1              2.0
12             41.79            3            1              3.0
14              9.91            1            0              2.0

    Traffic_Conditions  Weather  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0                    1        0       3.56         0.80             0.32
2                    0        0       2.70         1.21             0.15
5                    2        0       2.55         1.71             0.48
12                   0        0       4.60         1.77             0.11
14                   0        0       2.32         1.26             0.34

    Trip_Duration_Minutes
0                   53.82
2                   37.27
5                   89.33
12                  86.95
14                  41.72
0     36.2624
2     52.9032
5     60.2028
12    88.1328
14    28.9914
Name: Trip_Price, dtype: float64

cek shape

In [11]:
print("Feature :", X.shape)

print("Target :", y.shape)

Feature : (562, 10)
Target : (562,)

train test split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

meliat ukuran data

In [14]:
print("Training :", X_train.shape)

print("Testing :", X_test.shape)

Training : (449, 10)
Testing : (113, 10)

stabdart scaler

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

fit transform

In [18]:
X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

simpan scaler

In [19]:
import joblib
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

cek bentuk data

In [20]:
print(X_train.shape)

print(X_test.shape)

(449, 10)
(113, 10)

simpan dataset yang sudah diproses

In [21]:
processed_df = pd.concat([X, y], axis=1)

processed_df.to_csv("../dataset/processed_taxi.csv", index=False)